### PR TITLE
adding index

### PR DESCRIPTION
**Pull request by MDerricott**

### CODE REVIEW

**Review by Ryan-T-Case — APPROVED** [review]
I dont actually approve

**Comment by aosilvester** [comment]
this is where i would approve. if i did....

**Review by Ryan-T-Case — APPROVED** [review]
I still dont approve

**Review by MDerricott — COMMENTED** [review]
can I review my own stuff?

**Review by JennyLiang804 — APPROVED** [review]
i approve

**Comment by Ryan-T-Case** [comment]
I will never approve

**Review by aosilvester — APPROVED** [review]
my second attempt at disapproving this

**Pull request merged**
